import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import '@/app/globals.css';
import Providers from '@/app/providers';
import { Layout, Wrapper } from '@/components/shared/layout';
import { cn } from '@/lib/tailwind';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Inscribed Bommy',
  description: 'Generated by @aiiiden0',
};

export default async function RootLayout({
  children,
  navbar,
  footer,
}: {
  children: React.ReactNode;
  navbar: React.ReactNode;
  footer: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-orange-950/20 font-sans antialiased',
          fontSans.variable,
        )}
      >
        <Providers>
          <Wrapper>
            <Layout navbar={navbar} footer={footer}>
              {children}
            </Layout>
          </Wrapper>
        </Providers>
      </body>
    </html>
  );
}
